"""empty message

Revision ID: 385abec0231f
Revises: 615c1a383140
Create Date: 2025-08-05 17:30:29.244349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385abec0231f'
down_revision = '615c1a383140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dasi_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dasi_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dasi_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dasi_answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('phq4_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phq4_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phq4_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phq4_answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pgsga_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pgsga_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pgsga_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pgsga_answers', sa.JSON(), nullable=True))
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=True))
        batch_op.drop_column('pgsga_answers')
        batch_op.drop_column('pgsga_level')
        batch_op.drop_column('pgsga_score')
        batch_op.drop_column('pgsga_type')
        batch_op.drop_column('phq4_answers')
        batch_op.drop_column('phq4_level')
        batch_op.drop_column('phq4_score')
        batch_op.drop_column('phq4_type')
        batch_op.drop_column('dasi_answers')
        batch_op.drop_column('dasi_level')
        batch_op.drop_column('dasi_score')
        batch_op.drop_column('dasi_type')

    # ### end Alembic commands ###
