"""Fix email index issue

Revision ID: 4ac507a7e148
Revises: 
Create Date: 2025-07-19 20:48:52.345815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ac507a7e148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaires')
    op.drop_table('users')
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('dasi', 'phq4', 'pgsga', collation='utf8mb4_unicode_520_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=mysql.ENUM('universal', 'targeted', 'specialist', collation='utf8mb4_unicode_520_ci'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('answers',
               existing_type=mysql.JSON(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=mysql.JSON(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('universal', 'targeted', 'specialist', collation='utf8mb4_unicode_520_ci'),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('dasi', 'phq4', 'pgsga', collation='utf8mb4_unicode_520_ci'),
               existing_nullable=False)
        batch_op.drop_column('status')

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), nullable=False),
    sa.Column('gender', mysql.ENUM('male', 'female', 'other'), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('medical_id', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20), nullable=False),
    sa.Column('role', mysql.ENUM('user', 'nurse', 'doctor'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('questionnaires',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('dasi', 'phq4', 'pgsga'), nullable=False),
    sa.Column('score', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('level', mysql.ENUM('universal', 'targeted', 'specialist'), nullable=False),
    sa.Column('answers', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.Column('submitted_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('questionnaires_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
