"""empty message

Revision ID: 615c1a383140
Revises: 4ac507a7e148
Create Date: 2025-08-05 17:09:28.226806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '615c1a383140'
down_revision = '4ac507a7e148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('questionnaire_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('score')
        batch_op.drop_column('type')
        batch_op.drop_column('answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50), nullable=False))
        batch_op.add_column(sa.Column('score', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questionnaire_ibfk_1'), 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('level',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
