"""empty message

Revision ID: 9a18b3944abf
Revises: fdf6e7a38f73
Create Date: 2025-08-11 20:56:55.300960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a18b3944abf'
down_revision = 'fdf6e7a38f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('answered_at')
        batch_op.drop_column('answer')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('answer', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
        batch_op.add_column(sa.Column('answered_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('question_ibfk_2'), 'user', ['doctor_id'], ['id'])

    # ### end Alembic commands ###
