"""empty message

Revision ID: fdf6e7a38f73
Revises: 385abec0231f
Create Date: 2025-08-10 08:31:56.761580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf6e7a38f73'
down_revision = '385abec0231f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chi_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tumor_type', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['chi_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tumor_type')
        batch_op.drop_column('chi_number')

    # ### end Alembic commands ###
